import hotel1 from '../Assets/images/Rectangle 26.png';
import hotel2 from '../Assets/images/Rectangle 27.png';
import hotel3 from '../Assets/images/Rectangle 28.png';

const Hotel = [
  {
    id: '1',
    key: 'Sajek1',
    img: hotel1,
    place: 'Sajek',
    title: 'Light bright airy stylish apt & safe peaceful stay',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.9 (20)',
    price: '34',
    totalPrice: '167',
  },
  {
    id: '2',
    key: 'Sajek2',
    img: hotel2,
    place: 'Sajek',
    title: 'Apartment in Lost Panorama',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.8 (10)',
    price: '52',
    totalPrice: '167',
  },
  {
    id: '3',
    key: 'Sajek3',
    img: hotel3,
    place: 'Sajek',
    title: 'AR Lounge & Pool (r&r + b&b)',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.9 (25)',
    price: '44',
    totalPrice: '167',
  },
  {
    id: '4',
    key: 'Sreemangal4',
    img: hotel1,
    place: 'Sreemangal',
    title: 'Light bright airy stylish apt & safe peaceful stay',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.9 (20)',
    price: '34',
    totalPrice: '167',
  },
  {
    id: '5',
    key: 'Sreemangal5',
    img: hotel2,
    place: 'Sreemangal',
    title: 'Apartment in Lost Panorama',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.8 (10)',
    price: '52',
    totalPrice: '167',
  },
  {
    id: '6',
    key: 'Sreemangal6',
    img: hotel3,
    place: 'Sreemangal',
    title: 'AR Lounge & Pool (r&r + b&b)',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.9 (25)',
    price: '44',
    totalPrice: '167',
  },
  {
    id: '7',
    key: 'Sundorbon7',
    img: hotel1,
    place: 'Sundorbon',
    title: 'Light bright airy stylish apt & safe peaceful stay',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.9 (20)',
    price: '34',
    totalPrice: '167',
  },
  {
    id: '8',
    key: 'Sundorbon8',
    img: hotel2,
    place: 'Sundorbon',
    title: 'Apartment in Lost Panorama',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.8 (10)',
    price: '52',
    totalPrice: '167',
  },
  {
    id: '9',
    key: 'Sundorbon9',
    img: hotel3,
    place: 'Sundorbon',
    title: 'AR Lounge & Pool (r&r + b&b)',
    room: '4 guests 2 bedrooms 2 beds 2 baths',
    wifi: 'Wif Air conditioning Kitchen',
    cancel: 'Cancellation fexibility availiable',
    rating: '4.9 (25)',
    price: '44',
    totalPrice: '167',
  },
]

export default Hotel;